apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: notify-deployment
  labels:
    app: notificationservice
spec:
  selector:
    matchLabels:
      app: notificationservice
      kube-monkey/enabled: "enabled"
      kube-monkey/identifier: "notificationservice"
      kube-monkey/mtbf: '2'
      kube-monkey/kill-mode: "fixed"
      kube-monkey/kill-value: "1"

  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: notificationservice
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "notificationservice"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"

    spec:
      containers:
      - name: notificationservice
        image: chaitrali1805/notification-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  labels:
    app: notificationservice
spec:
  type: LoadBalancer
  # loadBalancerIP: 10.10.10.10
  ports:
  - port: 5001
    targetPort: 5001
    name: http
    protocol: TCP
    nodePort: 30004
  selector:
    app: notificationservice
  externalIPs:
  - 149.165.171.144

