apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: uideployment
  labels:
    app: userinterface
spec:
  selector:
    matchLabels:
      app: userinterface
      kube-monkey/enabled: "enabled"
      kube-monkey/identifier: "userinterface"
      kube-monkey/mtbf: '2'
      kube-monkey/kill-mode: "fixed"
      kube-monkey/kill-value: "1"

  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: userinterface
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "userinterface"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"

    spec:
      containers:
      - name: userinterface
        image: chaitrali1805/user-interface:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: userinterface
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  labels:
    app: userinterface
spec:
  type: LoadBalancer
  # loadBalancerIP: 10.10.10.10
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30001
  selector:
    app: userinterface
  externalIPs:
  - 149.165.171.144

