version: "2"

services:
  ms:
    build: "."
    image: userservice_ms
    restart: always
    ports:
      - "8086:8086"
    links:
      - db
    depends_on:
      - db
    networks:
      - host
networks:
  host:
    driver: "bridge"
